### PR TITLE
Add code coverage.

### LINKED ISSUE #52: Add code coverage
Add code coverage and thresholds based on the current coverage.

### PR DESCRIPTION
**Pull request by julianusti**
This PR contains test coverage configuration with `nyc`.

If it also makes sense I can do a separate PR, where I'd like to add `pre-commit` hook, which will run `test-cov` script.

Close #52

### CODE REVIEW

**Comment by grassator** [comment]
@julianusti thank you for the PR, could you please rebase. Ideally also please do an interactive rebase so that we do not have commits with repeating messages and merge commits,

**Comment by julianusti** [comment]
@dmitrykrivaltsevich done.

**Comment by grassator** [comment]
👍

**Comment by shuhei** [comment]
:+1:

**Pull request merged**
