### PR TITLE
upgrade jsdoc-to-markdown from 3.0.2 -> 4.0.1

### PR DESCRIPTION
**Pull request by aryszka**
fixing vulnerabilities in dependencies: handlebars, marked, uglify-js

(i haven't tested, is there a way to run the vulnerability check on a branch?)

### CODE REVIEW

**Comment by grassator** [comment]
@aryszka thanks for this. Since we are adding `package-lock.json`, would be great if we also use ranges instead of fixed versions for all dependencies, but could be a separate PR.

**Comment by grassator** [comment]
👍

**Comment by aryszka** [comment]
:+1:

**Comment by aryszka** [comment]
ok, will push the ranges setting some time

**Pull request merged**
