### PR TITLE
README: Improve grammar

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR edits the README to make it easier to read.

- use `ServiceClient` instead of the word `Serviz`
- tiny grammar fixes

### CODE REVIEW

**Comment by shuhei** [comment]
👍

**Comment by shuhei** [comment]
@olleolleolle Thanks a lot!

**Comment by olleolleolle** [comment]
You're running a thoughtful, cool project.

**Comment by mroderick** [comment]
👍

**Comment by grassator** [comment]
👍

**Pull request merged**
