### PR TITLE
Documented dropRequestAfter field

### PR DESCRIPTION
**Pull request by jans510**
Documented dropRequestAfter field

### CODE REVIEW

**Comment by jans510** [comment]
:+1:

**Comment by grassator** [comment]
👍

**Comment by shuhei** [comment]
👍

**Comment by grassator** [comment]
👍

**Comment by mo-gr** [comment]
👍

**Comment by grassator** [comment]
@jans510 thanks!

**Comment by jans510** [comment]
@grassator you're welcome, thanks for pointing out that this parameter exists.

**Pull request merged**
