### PR TITLE
Add a check for empty response body.

### PR DESCRIPTION
**Pull request by varunpal**
Fix for responses which just return 204.

### CODE REVIEW

**Comment by grassator** [comment]
@varunpal Could you please add a test that checks for this behavior?

**Comment by varunpal** [comment]
@grassator added test.

**Comment by grassator** [comment]
@varunpal Unfortunately the description to the PR doesn't actually match the implementation and the HTTP spec. The Content-Type and the body indeed should be ignored, but only with 204 status code, so that should be the check in the test and in the code, rather than just for empty body. Any other status code with an empty body is a bad response from the server.

**Comment by varunpal** [comment]
@grassator made the changes.

**Comment by grassator** [comment]
👍

**Comment by grassator** [comment]
@varunpal I've released a new version `0.1.5` on NPM

**Pull request merged**
